version: '3'

services: 

  node:
    image: silviotmalmeida/node:prod
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ./app:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      