version: '3'

services: 

  laravel:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: silviotmalmeida/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx.prod
    image: silviotmalmeida/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge      