# definindo a imagem base
FROM node:15

# definindo a pasta de trabalho a ser criada e focada no acesso
WORKDIR /usr/src/app

# expondo a porta para acesso de outros containers
EXPOSE 3000

# copiando os arquivos do app para a pasta de trabalho
COPY app .

# definindo o comando a ser executado após a inicialização
# comando fixo
# se existir um ENTRYPOINT em imagem anterior, este conteúdo substituirá o anterior
# iniciando o app
ENTRYPOINT [ "node","index.js" ]