# definindo a imagem base
FROM nginx:1.15.0-alpine

# comandos a serem executados
## apagando as configurações default
RUN rm /etc/nginx/conf.d/default.conf

# copiando o arquivo de configuração customizado
COPY nginx.conf /etc/nginx/conf.d